services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGSSLMODE=${PGSSLMODE}
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

  ollama:
    build:
      context: ./ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

networks:
  app-network:
    driver: bridge
